version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/base:stable
    parallelism: 1
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Setup"
          command: "sudo apt update && sudo apt install -y clang cmake ninja-build"
      - run:
          name: "Build"
          command: "mkdir debug && cd debug && cmake .. -G Ninja && ninja"
      - run:
          name: "Test"
          command: "cd debug/tests && ./parallel-factorial-test --gtest_output=xml"
      - store_test_results:
          path: "debug/tests/test_detail.xml"

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
